services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
  php:
    build: .
    volumes:
      - ./:/code
    networks:
      - app-network
networks:
  app-network:


